### ISSUE TITLE
Looking for "wantedold" aso. line in the main.py file

### ISSUE THREAD

**Issue by Nebelwacht** [pan324/anno1800_seedfinder#8]
Hey there, 

do you have removed the "wanted" island entry? And is there a way to still filter for specific wanted islands? 

Used your programm in april this year and really loved it. Wanted to find one "final" seed now, since its the last DLC we get. But sadly i can't find the "wantedold" line anymore that i used a lot during my last search. 

Best wishes 
Nebel

**Comment by pan324** [comment]
I have removed the option because the score table achieves almost the same effect. While unwanted islands massively speed up the computation, wanted islands do not. 

To enforce wanted islands with the score table, one can add 1000000 to the score of every wanted island. The only difference is that this will not discriminate between old world and cape. Though if an island is that awesome that it should be part of one world, it should probably also be found in the other.

**Comment by Nebelwacht** [comment]
Hi, i played around with with score table a bit and its working well enough =D 
But i'm running into another limitation. With the old "wanted" option, i could differentiate between cap and old world. Now the score tables count for both maps. I can't even trick the system with blocking some maps for e.g. cap, since the "unwanted" option is also for both maps combined. 
Is there any way how i can differentiate for old world and cap?

**Comment by luizvictorsq** [comment]
With the map editor, I have the new files a7t and assets (modded). How can I check these map to understand the best seed for it?

**Comment by pan324** [comment]
You would need to run the preprocessing scripts yourself. The code works like this:

1. maptemplatestocsv.py runs first and creates the overview here: https://github.com/pan324/anno1800_seedfinder/blob/main/templates/templates.csv Basically this contains pairs of TemplateFilename (a path) vs the game settings (map size and type and so on).
2. maptocsv.py runs next and goes over all TemplateFilenames. It retrieves each map data and stores it.

Afterwards the main.py code should work as usual. You probably don't even need to do step 1 if the mod just overrides a certain map type (e.g. Archipelago Large Large or something). The only thing that might need help is step 2 where it tries to go over all TemplateFilenames. I'm not sure where the modded data is located. If it's the same place as usual then just running the maptocsv.py should work. They expect that the repository has two neighboring folders, one for the FileDBReader and one for all game assets as extracted with the RDAExplorer. I.e. the folders ../FileDBReader and ../data should exist.

**Comment by luizvictorsq** [comment]
> You would need to run the preprocessing scripts yourself. The code works like this:
> 
> 1. maptemplatestocsv.py runs first and creates the overview here: https://github.com/pan324/anno1800_seedfinder/blob/main/templates/templates.csv Basically this contains pairs of TemplateFilename (a path) vs the game settings (map size and type and so on).
> 2. maptocsv.py runs next and goes over all TemplateFilenames. It retrieves each map data and stores it.
> 
> Afterwards the main.py code should work as usual. You probably don't even need to do step 1 if the mod just overrides a certain map type (e.g. Archipelago Large Large or something). The only thing that might need help is step 2 where it tries to go over all TemplateFilenames. I'm not sure where the modded data is located. If it's the same place as usual then just running the maptocsv.py should work. They expect that the repository has two neighboring folders, one for the FileDBReader and one for all game assets as extracted with the RDAExplorer. I.e. the folders ../FileDBReader and ../data should exist.

Thank you for the explanation. I am having this issue after first run in maptemplatestocsv.py === RESTART: D:\Anno 1800 mods\anno1800_seedfinder-main\maptemplatestocsv.py ===
Traceback (most recent call last):
  File "D:\Anno 1800 mods\anno1800_seedfinder-main\maptemplatestocsv.py", line 55, in <module>
    TemplatesToCsv()
  File "D:\Anno 1800 mods\anno1800_seedfinder-main\maptemplatestocsv.py", line 43, in TemplatesToCsv
    df = pd.read_xml(ASSET_PATH, xpath=".//MapTemplate").dropna(axis=1,how="all")
  File "D:\Python\Lib\site-packages\pandas\io\xml.py", line 1118, in read_xml
    return _parse(
  File "D:\Python\Lib\site-packages\pandas\io\xml.py", line 844, in _parse
    data_dicts = p.parse_data()
  File "D:\Python\Lib\site-packages\pandas\io\xml.py", line 564, in parse_data
    self.xml_doc = self._parse_doc(self.path_or_buffer)
  File "D:\Python\Lib\site-packages\pandas\io\xml.py", line 655, in _parse_doc
    document = fromstring(
  File "src\lxml\etree.pyx", line 3257, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1916, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1803, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1144, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

**Comment by luizvictorsq** [comment]
Even If I put the map on same folder of the directory stated in templates.csv

When I ran the maptocsv.py, i got this
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

======== RESTART: D:\Anno 1800 mods\anno1800_seedfinder-main\maptocsv.py =======
data/sessions/maps/pool/moderate/moderate_archipel_ll_01/moderate_archipel_ll_01.a7t
data/sessions/maps/pool/moderate/moderate_archipel_lm_01/moderate_archipel_lm_01.a7t
data/sessions/maps/pool/moderate/moderate_archipel_ls_01/moderate_archipel_ls_01.a7t
data/sessions/maps/pool/moderate/moderate_archipel_ml_01/moderate_archipel_ml_01.a7t
data/sessions/maps/pool/moderate/moderate_archipel_mm_01/moderate_archipel_mm_01.a7t
data/sessions/maps/pool/moderate/moderate_archipel_ms_01/moderate_archipel_ms_01.a7t
data/sessions/maps/pool/moderate/moderate_archipel_sl_01/moderate_archipel_sl_01.a7t
data/sessions/maps/pool/moderate/moderate_archipel_sm_01/moderate_archipel_sm_01.a7t
data/sessions/maps/pool/moderate/moderate_archipel_ss_01/moderate_archipel_ss_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_ll_01/moderate_atoll_ll_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_lm_01/moderate_atoll_lm_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_ls_01/moderate_atoll_ls_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_ml_01/moderate_atoll_ml_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_mm_01/moderate_atoll_mm_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_ms_01/moderate_atoll_ms_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_sl_01/moderate_atoll_sl_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_sm_01/moderate_atoll_sm_01.a7t
data/sessions/maps/pool/moderate/moderate_atoll_ss_01/moderate_atoll_ss_01.a7t
data/sessions/maps/pool/moderate/moderate_corners_ll_02/moderate_corners_ll_02.a7t
data/sessions/maps/pool/moderate/moderate_corners_lm_01/moderate_corners_lm_01.a7t
data/sessions/maps/pool/moderate/moderate_corners_ls_01/moderate_corners_ls_01.a7t
data/sessions/maps/pool/moderate/moderate_corners_ml_01/moderate_corners_ml_01.a7t
data/sessions/maps/pool/moderate/moderate_corners_mm_01/moderate_corners_mm_01.a7t
data/sessions/maps/pool/moderate/moderate_corners_ms_01/moderate_corners_ms_01.a7t
data/sessions/maps/pool/moderate/moderate_corners_sl_01/moderate_corners_sl_01.a7t
data/sessions/maps/pool/moderate/moderate_corners_sm_01/moderate_corners_sm_01.a7t
data/sessions/maps/pool/moderate/moderate_corners_ss_01/moderate_corners_ss_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_ll_01/moderate_islandarc_ll_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_lm_01/moderate_islandarc_lm_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_ls_01/moderate_islandarc_ls_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_ml_01/moderate_islandarc_ml_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_mm_01/moderate_islandarc_mm_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_ms_01/moderate_islandarc_ms_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_sl_01/moderate_islandarc_sl_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_sm_01/moderate_islandarc_sm_01.a7t
data/sessions/maps/pool/moderate/moderate_islandarc_ss_01/moderate_islandarc_ss_01.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_ll_02/moderate_snowflake_ll_02.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_lm_01/moderate_snowflake_lm_01.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_ls_01/moderate_snowflake_ls_01.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_ml_01/moderate_snowflake_ml_01.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_mm_01/moderate_snowflake_mm_01.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_ms_01/moderate_snowflake_ms_01.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_sl_01/moderate_snowflake_sl_01.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_sm_01/moderate_snowflake_sm_01.a7t
data/sessions/maps/pool/moderate/moderate_snowflake_ss_01/moderate_snowflake_ss_01.a7t
data/sessions/maps/pool/colony01/colony01_s_01/colony01_s_01.a7t
data/sessions/maps/pool/colony01/colony01_s_02/colony01_s_02.a7t
data/sessions/maps/pool/colony01/colony01_s_03/colony01_s_03.a7t
data/sessions/maps/pool/colony01/colony01_m_01/colony01_m_01.a7t
data/sessions/maps/pool/colony01/colony01_m_02/colony01_m_02.a7t
data/sessions/maps/pool/colony01/colony01_m_03/colony01_m_03.a7t
data/sessions/maps/pool/colony01/colony01_l_01/colony01_l_01.a7t
data/sessions/maps/pool/colony01/colony01_l_02/colony01_l_02.a7t
data/sessions/maps/pool/colony01/colony01_l_03/colony01_l_03.a7t
data/sessions/maps/campaign/moderate/campaign_chapter01_moderate_01/campaign_chapter01_moderate_01.a7t
data/sessions/maps/campaign/colony01/campaign_chapter03_colony01/campaign_chapter03_colony01.a7t
data/dlc01/sessions/maps/sunken_treasures/moderate_continental_01/moderate_c_01.a7t
data/dlc03/sessions/maps/colony_03_sp/colony_03_sp.a7t
data/dlc06/sessions/maps/land_of_lions/colony02_01/colony02_01.a7t
data/dlc06/sessions/maps/land_of_lions/colony02_01_mp/colony02_01_mp.a7t
data/dlc10/scenario02/sessions/maps/scenario_02_colony_01/scenario_02_colony_01.a7t
data/dlc11/scenario03/sessions/maps/scenario_03_colony_01/scenario_03_colony_01.a7t
data/dlc12/scenario04/sessions/maps/scenario_04_colony_01/scenario_04_colony_01.a7t
data/eoy21/sessions/maps/green_game_jam/ggj_colony01_01/ggj_colony01_01.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_s_01/colony01_s_01_dlc12enlarged.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_s_02/colony01_s_02_dlc12enlarged.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_s_03/colony01_s_03_dlc12enlarged.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_m_01/colony01_m_01_dlc12enlarged.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_m_02/colony01_m_02_dlc12enlarged.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_m_03/colony01_m_03_dlc12enlarged.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_l_01/colony01_l_01_dlc12enlarged.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_l_02/colony01_l_02_dlc12enlarged.a7t
data/dlc12/sessions/maps/pool/colony01/colony01_l_03/colony01_l_03_dlc12enlarged.a7t
data/dlc12/sessions/maps/campaign/colony01/campaign_chapter03_colony01/campaign_chapter03_colony01_dlc12enlarged.a7t
data/sessions/maps/pool/moderate/moderate_archipel_ll_01/moderate_archipel_ll_01.a7t
Traceback (most recent call last):
  File "D:\Anno 1800 mods\anno1800_seedfinder-main\maptocsv.py", line 60, in <module>
    tree = ET.parse(root+"/"+path[:-4]+".xml")
  File "D:\Python\Lib\xml\etree\ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "D:\Python\Lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/sessions/maps/pool/moderate/moderate_archipel_ll_01/moderate_archipel_ll_01.xml'

**Comment by luizvictorsq** [comment]
I reinstalled python once again.

Same error
Traceback (most recent call last):
  File "D:\Anno 1800 mods\anno1800_seedfinder-main\maptocsv.py", line 60, in <module>
    tree = ET.parse(root+"/"+path[:-4]+".xml")
  File "C:\Users\Luiz Victor\AppData\Local\Programs\Python\Python311\Lib\xml\etree\ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "C:\Users\Luiz Victor\AppData\Local\Programs\Python\Python311\Lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/sessions/maps/pool/moderate/moderate_archipel_ll_01/moderate_archipel_ll_01.xml'

**Comment by FR444** [comment]
The code expects a full dump of all game files, or at least all TemplateFilename entries to exist. I'm not sure what that mod looks like but you could circumvent it like this:

1) In templates.csv, remove all lines except the one that matches your setting (Archipelago, etc.)
2) In templates.csv, change TemplateFilename to the name of your .a7t file. E.g. set TemplateFilename to data/yourfilename.a7t and then place the file to D:\Anno 1800 mods\data\yourfilename.a7t

**Comment by luizvictorsq** [comment]
It doesnt have the xml, the file is there, but it seems to being asked to have a xml file.

**Comment by pan324** [comment]
All right, now that is puzzling. 

I have noticed an issue where FileDBReader does not complain (through a return value different from 0) when a file is not found. This matches your error fairly well. The initial loop (to convert a7tinfo to xml) prints out all files but does not create any xmls without noticing. Then the proper loop to read the xml files instantly fails with the first file. 

Can you try this function in maptocsv.py? It will only complain a bit earlier if this is indeed the issue.

```
def CreateXmls():
    """Convert a7tinfo files into xml files, placed next to them."""
    try: os.makedirs(outdir)
    except FileExistsError: pass
    for path in paths:  # Path to .a7t files.
        print(path)
        path = root+"/"+path+"info"
        assert os.path.exists(path), "Cannot create XML: "+path+" does not exist"
        cmd = os.path.normpath(r"../FileDBReader/FileDBReader.exe decompress -y -f "+path)
        rv = os.system(cmd)
        if rv:
            raise Exception("Could not run cmd. FileDBReader not found?")
```

Can you also lay out the exact (relevant) modded files that you have? E.g. does the mod override data/sessions/maps/pool/moderate/moderate_archipel_ll_01/moderate_archipel_ll_01 or a similar file? Is it specified as xml or as a7tinfo?

**Comment by luizvictorsq** [comment]
It override the file. in the original folder, there is no xml, so I presume the python code would create it.

**Comment by luizvictorsq** [comment]
It has the a7info.
I can upload it here and you can run the seed?

**Comment by luizvictorsq** [comment]
[[Map] Novo Corner.zip](https://github.com/pan324/anno1800_seedfinder/files/11456707/Map.Novo.Corner.zip)

**Comment by luizvictorsq** [comment]
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

======== RESTART: D:\Anno 1800 mods\anno1800_seedfinder-main\maptocsv.py =======
[Map] Novo Corner/data/ame/maps/pool/moderate/moderate_atoll_ll.a7t
Traceback (most recent call last):
  File "D:\Anno 1800 mods\anno1800_seedfinder-main\maptocsv.py", line 53, in <module>
    CreateXmls()
  File "D:\Anno 1800 mods\anno1800_seedfinder-main\maptocsv.py", line 30, in CreateXmls
    assert os.path.exists(path), "Cannot create XML: "+path+" does not exist"
AssertionError: Cannot create XML: ../[Map] Novo Corner/data/ame/maps/pool/moderate/moderate_atoll_ll.a7tinfo does not exist

**Comment by luizvictorsq** [comment]
[templates.csv](https://github.com/pan324/anno1800_seedfinder/files/11456750/templates.csv)

**Comment by luizvictorsq** [comment]
Well I put everything in a new folder, like new, changed the templates

run the first time, filedb was open and closing... in the end got error, i replaced the code you posted; ran again and got new message.

=============== RESTART: D:\anno1800_seedfinder-main\maptocsv.py ===============
data/moderate_atoll_ll.a7t
data/moderate_atoll_lm.a7t
data/moderate_atoll_ls.a7t
data/moderate_atoll_ml.a7t
data/moderate_atoll_mm.a7t
data/moderate_atoll_ms.a7t
data/moderate_atoll_sl.a7t
data/moderate_atoll_sm.a7t
data/moderate_atoll_ss.a7t
data/moderate_atoll_ll.a7t
Traceback (most recent call last):
  File "D:\anno1800_seedfinder-main\maptocsv.py", line 60, in <module>
    tree = ET.parse(root+"/"+path[:-4]+".xml")
  File "C:\Users\Luiz Victor\AppData\Local\Programs\Python\Python311\Lib\xml\etree\ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "C:\Users\Luiz Victor\AppData\Local\Programs\Python\Python311\Lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/moderate_atoll_ll.xml'

===================================== RESTART: D:\anno1800_seedfinder-main\maptocsv.py ====================================
data/moderate_atoll_ll.a7t
Traceback (most recent call last):
  File "D:\anno1800_seedfinder-main\maptocsv.py", line 54, in <module>
    CreateXmls()
  File "D:\anno1800_seedfinder-main\maptocsv.py", line 30, in CreateXmls
    assert os.path.exists(path), "Cannot create XML: "+path+" does not exist"
AssertionError: Cannot create XML: ../data/moderate_atoll_ll.a7tinfo does not exist

**Comment by luizvictorsq** [comment]
> All right, now that is puzzling.
> 
> I have noticed an issue where FileDBReader does not complain (through a return value different from 0) when a file is not found. This matches your error fairly well. The initial loop (to convert a7tinfo to xml) prints out all files but does not create any xmls without noticing. Then the proper loop to read the xml files instantly fails with the first file.
> 
> Can you try this function in maptocsv.py? It will only complain a bit earlier if this is indeed the issue.
> 
> ```
> def CreateXmls():
>     """Convert a7tinfo files into xml files, placed next to them."""
>     try: os.makedirs(outdir)
>     except FileExistsError: pass
>     for path in paths:  # Path to .a7t files.
>         print(path)
>         path = root+"/"+path+"info"
>         assert os.path.exists(path), "Cannot create XML: "+path+" does not exist"
>         cmd = os.path.normpath(r"../FileDBReader/FileDBReader.exe decompress -y -f "+path)
>         rv = os.system(cmd)
>         if rv:
>             raise Exception("Could not run cmd. FileDBReader not found?")
> ```
> 
> Can you also lay out the exact (relevant) modded files that you have? E.g. does the mod override data/sessions/maps/pool/moderate/moderate_archipel_ll_01/moderate_archipel_ll_01 or a similar file? Is it specified as xml or as a7tinfo?

THis is the error i get

data/moderate_atoll_ll.a7t
Traceback (most recent call last):
  File "D:\anno1800_seedfinder-main\maptocsv.py", line 54, in <module>
    CreateXmls()
  File "D:\anno1800_seedfinder-main\maptocsv.py", line 30, in CreateXmls
    assert os.path.exists(path), "Cannot create XML: "+path+" does not exist"
AssertionError: Cannot create XML: ../data/moderate_atoll_ll.a7tinfo does not exist

**Comment by pan324** [comment]
All right. So I put the files in a data2 folder and adjusted the templates.csv to point to the right place.

```
TemplateFilename,IslandSize,TemplateSize,IsUsedByMapGenerator,TemplateRegion,TemplateMapType,EnlargeDLC,EnlargedTemplateFilename,EnlargedAdditionalDecoIslands,AdditionalDecoIslands,Campaign
...
data/sessions/maps/pool/moderate/moderate_archipel_ss_01/moderate_archipel_ss_01.a7t,Small,Small,1,Moderate,Archipelago,0,,0,0,0
data2/ame/maps/pool/moderate/moderate_atoll_ll.a7t,Large,Large,1,Moderate,Atoll,0,,0,0,0
...
```

This worked just fine. Due to the high number of large islands, the odds of finding riverless islands is tiny and in fact the tool warned that there were possibly no riverless seeds at all, but a full run found 24 riverless seeds:

```
958365509
464745164
1582643369
1480145966
851292460
1786125980
694948405
500194121
182917005
1403783254
201659128
1524317294
737305450
1564539652
1032792968
1671519324
226239070
1778691592
202830710
1739739167
706049493
1691563000
501905925
1911491461
```

Let me know how it goes.
